footprint:
  [[-0.2800, -0.1600], [-0.2800, 0.1600], [0.1200, 0.1600], [0.1200, -0.1600]]
#footprint_padding: 0.05

obstacle_layer:
  enabled: true
  max_obstacle_height: 2.0
  min_obstacle_height: 0.0
  origin_z: 0.0
  z_resolution: 0.2
  z_voxels: 10
  unknown_threshold: 2
  mark_threshold: 0
  footprint_clearing_enabled: true
  combination_method: 1
  track_unknown_space: true
  obstacle_range: 4.0
  raytrace_range: 5.0
  observation_sources: scan_master #point_cloud
  scan_master:
    {
      data_type: LaserScan,
      sensor_frame: laser,
      topic: /scan_master,
      observation_persistence: 0.0,
      marking: true,
      clearing: true,
    }

  point_cloud:
    {
      data_type: PointCloud2,
      sensor_frame: camera_link,
      topic: /camera/depth/color/points,
      observation_persistence: 0.0,
      marking: true,
      clearing: true,
      max_obstacle_height: 0.5,
      min_obstacle_height: 0.2,
    }

global_inflation_layer:
  enabled: false
  cost_scaling_factor: 1.0
  inflation_radius: 0.8

local_inflation_layer:
  enabled: true
  cost_scaling_factor: 0.15
  inflation_radius: 0.1

static_layer:
  enabled: false
  map_topic: /map

plugins:
  - { name: static_layer, type: "costmap_2d::StaticLayer" }
  - { name: obstacle_layer, type: "costmap_2d::ObstacleLayer" }
  - { name: global_inflation_layer, type: "costmap_2d::InflationLayer" }
  - { name: local_inflation_layer, type: "costmap_2d::InflationLayer" }
